source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '7.0'

inhibit_all_warnings!

pod 'MZDayPicker', :git => 'https://github.com/handl/MZDayPicker.git', :branch => 'hightlight_today'
podspec :path => "../LIYDateTimePicker.podspec"

target :LIYDateTimePickerExampleTests, :exclusive => true do
    pod 'Kiwi'
end
