source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '7.0'

inhibit_all_warnings!

pod 'JTCalendar', :git => 'https://github.com/kgellci/JTCalendar.git', :commit => '5204659eaf90b6187e00710eaa6edc8927101340' # This must be placed before LIYDateTimePicker

podspec :path => "../LIYDateTimePicker.podspec"

target :LIYDateTimePickerExampleTests, :exclusive => true do
    pod 'Kiwi'
end
